apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - rbac.yaml
secretGenerator:
  - name: target-kube-token
    type: Opaque
    files:
      - token=secrets/target-kube-token
images:
  - name: kube-policy-semaphore
    newName: quay.io/utilitywarehouse/kube-policy-semaphore
    newTag: latest
